# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk-browsers
        environment:
          AWS_REGION: eu-west-1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: gradle dependencies --no-daemon

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run unit tests
      - run:
          command: gradle ci_unit --no-daemon
          name: ci_unit
          environment:
            SERVER_URL: https://alpha.tramchester.com
            ENV: Dev
      - run:
          command: gradle integration --no-daemon
          name: integration
      - run:
          command: gradle upload --no-daemon
          name: upload
      - run:
          name: deployDev
          command: gradle deploy updateLB tidy --no-daemon
          environment:
            ENV: Dev
      - run:
          name: setupLocale
          command: |
            sudo sh -c 'echo en_GB.UTF-8 UTF-8 >> /etc/locale.gen'
            sudo locale-gen en_GB.UTF-8
            sudo update-locale en_GB.UTF-8
      - run:
          name: acceptance
          command: |
            mkdir -p ~/drivers
            wget -N https://github.com/mozilla/geckodriver/releases/download/v0.20.0/geckodriver-v0.20.0-linux64.tar.gz -P ~/drivers
            tar xvzf ~/drivers/geckodriver-v0.20.0-linux64.tar.gz -C ~/drivers
            sudo cp ~/drivers/geckodriver /usr/local/bin/
            sudo apt-get remove firefox-mozilla-build
            wget "https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=en-US" -O ~/firefox-latest.tar.bz2
            tar xjf ~/firefox-latest.tar.bz2 -C ~/
            sudo ln -sfv ~/firefox/firefox /usr/bin/firefox
            export LANG="en_GB.UTF-8"
            gradle appium --no-daemon
          environment:
            SERVER_URL: https://alpha.tramchester.com
      - store_test_results:
          path: ~/repo/build/test-results
      - store_artifacts:
          path: ~/repo/build/reports/tests
