server:
  applicationContextPath: /
  rootPath: /api/*
  applicationConnectors:
    - type: http
      port: 8080
  adminContextPath: /admin
  adminConnectors:
    - type: http
      port: 8081
  gzip:
    enabled: true
    bufferSize: 8KiB
    minimumEntitySize: 160B
secureHost: tramchester.com
staticAssetCacheTimeSeconds: 300
graphDBConfig:
  graphName: gm_rail.db
  neo4jPagecacheMemory: 1000m
distributionBucket: tramchester2dist
instanceDataUrl: http://169.254.169.254
gtfsSourceConfig:
  - name: tfgm
    dataPath: data/tram
    hasFeedInfo: true
    transportModes: [ tram ]
    transportModesWithPlatforms: [ Tram ]
    initialWaitMinutes: 13
    noServices: []
    markedInterchangesOnly: false
    additionalInterchanges: [9400ZZMAGMX,9400ZZMAPIC]
    compositeStationModes: []
    addWalksForClosed: true
    stationClosures: []
rail:
  dataPath: data/rail
  version: 697
  modes: [ Train, RailReplacementBus ]
  initialWaitMinutes: 60
remoteSources:
  - name: rail
    dataURL: ${RAIL_DATAURL:-s3://tramchester2dist/railData/ttis697.zip}
    dataCheckURL: ""
    dataPath: data/rail
    filename: rail_data.zip
    defaultExpiryDays: 1
  - name: tfgm
    dataURL: ${TRAM_DATAURL:- https://odata.tfgm.com/opendata/downloads/TfGMgtfsnew.zip}
    dataCheckURL: https://odata.tfgm.com/opendata/downloads/TfGMgtfsnew.zip
    dataPath: data/tram
    filename: tfgm_data.zip
    defaultExpiryDays: 1
  - name: naptanxml
    dataURL: ${NAPTAN_DATAURL:- https://naptan.api.dft.gov.uk/v1/access-nodes?dataFormat=xml}
    dataCheckURL: ""
    dataPath: data/naptan
    filename: ${NAPTAN_FILE:- NaPTAN.xml}
    defaultExpiryDays: 14
  - name: nptg
    dataURL: ${NPTG_DATAURL:- https://beta-naptan.dft.gov.uk/Download/File/Localities.csv}
    dataCheckURL: ""
    dataPath: data/nptg
    filename: Localities.csv
    defaultExpiryDays: 14
tfgmTramliveData:
  dataUrl: https://api.tfgm.com/odata/Metrolinks
  dataSubscriptionKey: ${TFGMAPIKEY:- ""}
  s3Bucket: tramchesterlivedata
  s3Prefix: ${PLACE:- "test"}
  refreshPeriodSeconds: 20
  maxNumberStationsWithoutMessages: 10
  maxNumberStationsWithoutData: 5
openLdb:
  accessToken: ${OPENLDB_APIKEY:- ""}
  wsdlLocation: config/OpenLDBWS.wsdl
cacheFolder: data/cache/gm
calcTimeoutMillis: 3500
bounds:
  minEastings: 370000
  minNorthings: 380000
  maxEasting: 398500
  maxNorthings: 414500
planningEnabled: true
neighbourConfig:
  maxNeighbourConnections: 3
  distanceToNeighboursKM: 0.2
  additional:
    - first: "9400ZZMAEDY"
      second: "EDIDBRY"
    - first: "9400ZZMAECC"
      second: "ECCLES"
    - first: "9400ZZMAAUL"
      second: "ASHONUL"
maxWait: 25
numberQueries: 3
queryInterval: 10
maxNumberResults: 5
maxWalkingConnections: 3
maxJourneyDuration: 125
nearestStopRangeKM: 1.6
nearestStopForWalkingRangeKM: 1.2
numOfNearestStopsToOffer: 5
numOfNearestStopsForWalking: 3
walkingMPH: 3.0
recentStopsToShow: 5
dataExpiryThreadhold: 3
changeAtInterchangeOnly: true
sendCloudWatchMetrics: true
cloudWatchMetricsFrequencyMinutes: 2

swagger:
  resourcePackage: com.tramchester.resources
  title: tramchester

logging:
  level: INFO

  appenders:
    - type: console
      threshold: INFO
    - type: syslog
      host: localhost
      port: 514
      threshold: WARN
    - type: file
      currentLogFilename: logs/tramchester_gm.log
      threshold: INFO
      archive: true
      archivedLogFilenamePattern: logs/tramchester_gm_%i.log
      archivedFileCount: 5
      timeZone: UTC
      maxFileSize: 50MB
