server:
  type: simple
  applicationContextPath: /
  rootPath: /api/*
  adminContextPath: /admin
  connector:
    type: http
    port: 8080

secureHost: tramchester.com
staticAssetCacheTimeSeconds: 300
graphDBConfig:
  graphName: databases/tramchesterAcceptance.db
  neo4jPagecacheMemory: 1000m
distributionBucket: tramchester2dist
gtfsSourceConfig:
  -
    name: tfgm
    dataPath: data/tram
    hasFeedInfo: true
    transportModes: [ tram ]
    transportModesWithPlatforms: [ Tram ]
    initialWaitMinutes: 13
    noServices: []
    markedInterchangesOnly: false
    additionalInterchanges: [9400ZZMAGMX,9400ZZMAPIC]
    compositeStationModes: []
    stationClosures: []
    addWalksForClosed: true
remoteSources:
  - name: rail
    dataURL: s3://tramchester2dist/railData/ttis411.zip
    dataCheckURL: ""
    dataPath: data/rail
    filename: rail_data.zip
    defaultExpiryDays: 1
  - name: tfgm
    dataURL: ${TRAM_DATAURL:- https://odata.tfgm.com/opendata/downloads/TfGMgtfsnew.zip}
    dataCheckURL: https://odata.tfgm.com/opendata/downloads/TfGMgtfsnew.zip
    dataPath: data/tram
    filename: tfgm_data.zip
    defaultExpiryDays: 1
  - name: naptanxml
    dataURL: https://naptan.api.dft.gov.uk/v1/access-nodes?dataFormat=xml
    dataCheckURL: ""
    dataPath: data/naptan
    filename: NaPTAN.xml
    defaultExpiryDays: 14
  - name: nptg
    dataURL: https://beta-naptan.dft.gov.uk/Download/File/Localities.csv
    dataCheckURL: ""
    dataPath: data/nptg
    filename: Localities.csv
    defaultExpiryDays: 14
rail:
  dataPath: data/rail
  version: 411
  modes: [ Train, RailReplacementBus ]
  initialWaitMinutes: 60
cacheFolder: data/cache
calcTimeoutMillis: 3500
bounds:
  minEastings: 370000
  minNorthings: 380000
  maxEasting: 398500
  maxNorthings: 414500
tfgmTramliveData:
  dataUrl: https://api.tfgm.com/odata/Metrolinks
  dataSubscriptionKey: ${TFGMAPIKEY:- ""}
  s3Bucket: tramchesterlivedata
  s3Prefix: ${PLACE:- "test"}
  refreshPeriodSeconds: 20
  maxNumberStationsWithoutMessages: 10
  maxNumberStationsWithoutData: 5
instanceDataUrl: http://169.254.169.254
planningEnabled: true
neighbourConfig:
  maxNeighbourConnections: 3
  distanceToNeighboursKM: 0.2
  additional:
    - first: "9400ZZMAEDY"
      second: "EDIDBRY"
    - first: "9400ZZMAECC"
      second: "ECCLES"
    - first: "9400ZZMAAUL"
      second: "ASHONUL"
maxWait: 25
maxNumberResults: 5
maxJourneyDuration:  125
numberQueries: 3
queryInterval: 10
maxWalkingConnections: 3
nearestStopRangeKM: 1.6
nearestStopForWalkingRangeKM: 0.8
numOfNearestStopsToOffer:  5
numOfNearestStopsForWalking:  3
walkingMPH: 3
recentStopsToShow: 5
dataExpiryThreadhold: 3
changeAtInterchangeOnly: true
sendCloudWatchMetrics: false
cloudWatchMetricsFrequencyMinutes: 2

swagger:
  resourcePackage: com.tramchester.resources
  title: tramchester

logging:
  level: INFO
  loggers:
    root: INFO
    com.tramchester: INFO
    org.eclipse.jetty.servlet: INFO
    io.dropwizard.jersey.jackson: INFO

  appenders:
    - type: console
      threshold: WARN
    - type: syslog
      host: localhost
      port: 514
    - type: file
      currentLogFilename: build/reports/tests/accept_tramchester.log
      threshold: INFO
      archive: true
      archivedLogFilenamePattern: build/reports/tests/accept_tramchester-%d.log
      archivedFileCount: 5
      timeZone: UTC
